name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        toolchain:
          - stable
        include:
          - os: macos-latest
            toolchain: stable
          - os: windows-latest
            toolchain: stable
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust
        if: matrix.toolchain != 'minimal'
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Activate cache
        uses: Swatinem/rust-cache@v2

      - name: Build crate
        run: cargo build --verbose

      - name: Test crate
        run: cargo test --verbose

# vim:set et sts=2:
